### PR TITLE
V2 REST declares wrong response types in OpenAPI spec

### LINKED ISSUE #6210: Typescript: /v2/trees/{ref} Response nested inside of an object
**What happened**: GET /v2/trees/{ref} returns
```
{
   "reference":{
      "type":"BRANCH",
      "name":"main",
      "hash":"b5f61965b8822063ab67259a6edb7c1eb2a0d739a92aebac338feec7d4039e6f"
   }
}
```
Note: The same issue occurs for POST of the same URL (Creating a reference), the return value has the same nesting.

**What you expected to happen**:
Response should be as defined in the [Swagger definition](https://app.swaggerhub.com/apis/projectnessie/nessie/0.48.2#/v2-beta/getReferenceByNameV2):

```
{
  "type": "BRANCH",
  "hash": "2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d",
  "name": "main"
}
```

**How to reproduce it (as minimally and precisely as possible)**: Make a call to GET /v2/trees/-

**Details**:
- Nessie server type (docker/built from source) and version: Using 0.48.2 and confirmed the same behavior in 0.50.0
- Client type (Ex: UI/Spark/pynessie ...) and version: Browser

### PR DESCRIPTION
**Pull request by snazy**
A couple of response types in the V2 HttpTreeApi were incorrectly declared in the corresponding `@APIResponse`. Especialy `SingleReferenceResponse` was missing, also a few places where V2 now returns HTTP/200 (assign+delete) with the assigned/deleted reference.

Fixes #6210

### CODE REVIEW

**Review by adutra — CHANGES_REQUESTED** [review]

File: model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java [hunk 1]
```diff
@@ -129,7 +129,7 @@ public interface HttpTreeApi extends TreeApi {
           @Content(
               mediaType = MediaType.APPLICATION_JSON,
               examples = {@ExampleObject(ref = "refObjNew")},
-              schema = @Schema(implementation = Reference.class))
+              schema = @Schema(implementation = SingleReferenceResponse.class))
```
[the remark this answers is not in the document]
Comment (dimas-b) [reply model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java:132]: Yes, please update examples :+1:

File: model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java [hunk 2]
```diff
@@ -473,7 +489,7 @@ SingleReferenceResponse deleteReference(
             @Content(
                 mediaType = MediaType.APPLICATION_JSON,
                 examples = {@ExampleObject(ref = "iceberg")},
```
Comment (dimas-b) [inline model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java:491]: Please update this example too.

File: model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java [hunk 3]
```diff
@@ -176,8 +176,11 @@ SingleReferenceResponse createReference(
         content = {
           @Content(
               mediaType = MediaType.APPLICATION_JSON,
-              examples = {@ExampleObject(ref = "refObj")},
-              schema = @Schema(implementation = Reference.class))
+              examples = {
+                @ExampleObject(ref = "singleReferencesResponse"),
```
Comment (dimas-b) [inline model/src/main/java/org/projectnessie/api/v2/http/HttpTreeApi.java:180]: Quarkus swagger UI error (in browser): 
```
Resolver error at paths./api/v2/trees/{ref}.get.responses.200.content.application/json.examples.singleReferencesResponse.$ref
Could not resolve reference: Could not resolve pointer: /components/examples/singleReferencesResponse does not exist in document
```

It looks like a typo, it should probably be `singleReferenceResponse` (not plural, as in openapi.yaml).

File: model/src/main/resources/META-INF/openapi.yaml [hunk 4]
```diff
@@ -444,6 +373,139 @@ components:
...
+          name: "exampleBranch"
+
+    singleReferenceResponse:
+      value:
+        reference:
+          type: BRANCH
+          hash: "abcdef4242424242424242424242beef00dead42112233445566778899001122"
+          name: "exampleBranch"
+
+    singleReferencesResponseWithMetadata:
```
Comment (dimas-b) [inline model/src/main/resources/META-INF/openapi.yaml:431]: typo? Should this be `singleReferenceResponseWithMetadata` (singlular "reference") as above?

**Review by dimas-b — APPROVED** [review]
LGTM. Thanks @snazy !

**Review by adutra — APPROVED** [review]
