### PR TITLE
GC: Finally fix JDBC values specified via environment

### LINKED ISSUE #7405: nessie-gc: Some JDBC command line argument is still required even if it's fully configured via environment variables
When using the JDBC capability of nessie-gc (e.g. with Postgres), the CLI appears to not be "clever enough" to get fully configured by present environment variables and instead requires one of the CLI arguments to still be specified.

**What happened**:
Running any command that requires a database connection with `NESSIE_GC_JDBC_*` options in the current environment but without any of the `--jdbc-*` command line arguments, I get the following error message:

```
Error: Missing required argument (specify one of these): ([--inmemory] | [[--jdbc-url=<url>] [--jdbc-properties[=<String=String>[,<String=String>...]...]]... [[--jdbc-user=<user>] [--jdbc-password=<password>]]])
```

**What you expected to happen**:
I expected nessie-gc to get fully configured through the environment variables such that the command line arguments are not necessary anymore.

**How to reproduce it (as minimally and precisely as possible)**:
With a Postgres database running at `localhost:5432`, run the following command:
```bash
NESSIE_GC_JDBC_URL="jdbc:postgresql://localhost:5432/nessie_gc" NESSIE_GC_JDBC_USER=postgres NESSIE_GC_JDBC_PASSWORD=pass nessie-gc list
```
Observe the error message shown above.

**Details**:
- Nessie server type (docker/built from source) and version: Docker (on Kubernetes) v0.65.0
- Client type (Ex: UI/Spark/pynessie ...) and version: nessie-gc CLI v0.67.0

### PR DESCRIPTION
**Pull request by snazy**
Injecting default values via the environment works fine, even the values for JDBC username and password are requested from the default-values-provider. But unfortunately picocli does _not_ inject the valid `JdbcUserPassword` `@Command.ArgGroup`.

This change pulls the user/password fields into `JdbcOptions`. However, this change updates the behavior a little bit, by not requiring username and/or password to be present, the corresponding `Principal`s will only be injected, if the values are present.

Debug logging can be used to inspect the JDBC configuration (won't log the password though), for example like this:
```
NESSIE_GC_JDBC_URL="jdbc:..." NESSIE_GC_JDBC_USER="my-username" NESSIE_GC_JDBC_PASSWORD="very-secret" \
  java \
  -Dlog.level.console=DEBUG \
  -jar nessie-gc-tool-0.68.1-SNAPSHOT.jar \
  mark --jdbc
...
2023-08-25 12:41:54,515 [main] DEBUG o.p.g.c.j.AgroalJdbcDataSourceProvider - Connecting to JDBC URL jdbc:...
2023-08-25 12:41:54,516 [main] DEBUG o.p.g.c.j.AgroalJdbcDataSourceProvider - Connecting using name principal my-username
2023-08-25 12:41:54,516 [main] DEBUG o.p.g.c.j.AgroalJdbcDataSourceProvider - Connecting using given password principal
2023-08-25 12:41:54,516 [main] DEBUG o.p.g.c.j.AgroalJdbcDataSourceProvider - JDBC pool options: initial-size=2, max-size=5, min-size=2, connection-lifetime=PT5M, acquisition-timeout=PT10S
...
```

Fixes #7405

### CODE REVIEW

File: gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/AgroalJdbcDataSourceProvider.java [hunk 1]
```diff
@@ -126,6 +135,28 @@ public DataSource dataSource() throws SQLException {
...
         poolConfiguration.connectionFactoryConfiguration();
 
+    if (LOGGER.isDebugEnabled()) {
+      LOGGER.debug("Connecting to JDBC URL {}", jdbcUrl());
+      for (Object credential : credentials()) {
+        if (credential instanceof NamePrincipal) {
+          LOGGER.debug(
+              "Connecting using name principal {}", ((NamePrincipal) credential).getName());
+        } else if (credential instanceof SimplePassword) {
+          LOGGER.debug("Connecting using given password principal");
```
Comment (adutra) [inline gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/AgroalJdbcDataSourceProvider.java:145]:
```suggestion
          LOGGER.debug("Connecting using given password");
```

File: gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/AgroalJdbcDataSourceProvider.java [hunk 2]
```diff
@@ -126,6 +135,28 @@ public DataSource dataSource() throws SQLException {
...
+          System.err.println("WORD " + ((SimplePassword) credential).getWord());
```
Comment (adutra) [inline gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/AgroalJdbcDataSourceProvider.java:146]: But this _is_ logging the password, no?

Comment (snazy) [reply gc/gc-repository-jdbc/src/main/java/org/projectnessie/gc/contents/jdbc/AgroalJdbcDataSourceProvider.java:146]: argh - damn

**Review by dimas-b — APPROVED** [review]
