### PR TITLE
Fix NPE when fetching commit log with access checks enabled.

### LINKED ISSUE #7885: CEL-based Authorization rules are unable to process deleted entries
1. Start Nessie Server:
```
java -Dnessie.server.authorization.enabled=true \
  -Dnessie.server.authorization.rules.allow_all=true \
  -jar servers/quarkus-server/build/quarkus-app/quarkus-run.jar
``` 
2. Generate some entries using the content generator's `generate` command
3. Get commit log via `curl` (this works fine):
```
curl 'http://localhost:19120/api/v2/trees/main/history?fetch=ALL'
``` 
4. Delete an entry using the content generator's `delete` command
5. Get commit log using the same `curl` command as above, but now it fails:
```
{
  "status" : 500,
  "reason" : "Internal Server Error",
  "message" : "java.lang.NullPointerException: Cannot invoke \"org.projectnessie.model.ContentKey.toPathString()\" because the return value of \"org.projectnessie.services.authz.Check.key()\" is null",
  "errorCode" : "UNKNOWN",
  "serverStackTrace" : null
}
```

Server side exception:
```
2023-12-20 14:27:18,398 WARN  [org.pro.ser.res.exc.NessieExceptionMapper] (executor-thread-1) Unhandled exception returned as HTTP/500 to client: java.lang.NullPointerException: Cannot invoke "org.projectnessie.model.ContentKey.toPathString()" because the return value of "org.projectnessie.services.authz.Check.key()" is null
	at org.projectnessie.server.authz.CelBatchAccessChecker.canPerformOpOnPath(CelBatchAccessChecker.java:107)
	at org.projectnessie.server.authz.CelBatchAccessChecker.lambda$check$0(CelBatchAccessChecker.java:55)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.projectnessie.server.authz.CelBatchAccessChecker.check(CelBatchAccessChecker.java:49)
	at org.projectnessie.services.impl.TreeApiImpl.logEntryOperationsAccessCheck(TreeApiImpl.java:533)
	at org.projectnessie.services.impl.TreeApiImpl.getCommitLog(TreeApiImpl.java:468)
	at org.projectnessie.services.rest.RestTreeService_Subclass.getCommitLog$$superforward(Unknown Source)
	at org.projectnessie.services.rest.RestTreeService_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.projectnessie.services.rest.RestTreeService_Subclass.getCommitLog(Unknown Source)
	at org.projectnessie.services.rest.RestTreeService_ClientProxy.getCommitLog(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource.getCommitLog(RestV2TreeResource.java:239)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass.getCommitLog$$superforward(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass$$function$$7.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:38)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor.restMethodInvoke(QuarkusRestPathTemplateInterceptor.java:39)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass.getCommitLog(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource_ClientProxy.getCommitLog(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by adutra**
Fixes #7885.

This commit fixes a potential NPE when fetching commit log entries with fetch option `ALL` and access checks enabled.

The fix is twofold: first, fix `TreeApiImpl` that was incorrectly omitting content keys when creating checks for operations; when the identified key is not available; secondly, fix `CelBatchAccessChecker` that wasn't being resilient to empty script parameters.

### CODE REVIEW

File: servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java [hunk 1]
```diff
@@ -513,13 +513,15 @@ private LogEntry logEntryOperationsAccessCheck(
...
-      if (op instanceof Operation.Put) {
-        checks.add(canReadContentKey(endRef.getValue(), identifiedKeys.get(op.getKey())));
-      } else if (op instanceof Operation.Delete) {
-        checks.add(canReadContentKey(endRef.getValue(), identifiedKeys.get(op.getKey())));
-      } else {
+      if (!(op instanceof Operation.Put) && !(op instanceof Operation.Delete)) {
         throw new IllegalStateException("Unknown operation " + op);
       }
+      IdentifiedContentKey identifiedKey = identifiedKeys.get(op.getKey());
+      if (identifiedKey != null) {
```
Comment (dimas-b) [inline servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: I believe we actually have content IDs for `Delete` ops in the `StoreIndex` in the associated commit. I guess `VersionStore.getIdentifiedKeys()` should be able to discover keys for all operations. WDYT?

Comment (adutra) [reply servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: I thought about that too, but everything indicates that `getIdentifiedKeys` was designed to only handle PUT operations. The existing unit test does not test DELETE at all.

Let me play a bit with the idea though.

File: servers/quarkus-auth/src/main/java/org/projectnessie/server/authz/CelBatchAccessChecker.java [hunk 2]
```diff
@@ -77,65 +81,48 @@ private void canPerformOp(Check check, Map<Check, String> failed) {
...
   private void canPerformRepositoryConfig(Check check, Map<Check, String> failed) {
-    RepositoryConfig.Type repositoryConfigType = requireNonNull(check.repositoryConfigType());
+    String op = check.type().name();
+    String type =
+        Optional.ofNullable(check.repositoryConfigType())
+            .map(RepositoryConfig.Type::name)
+            .orElse("");
 
-    ImmutableMap<String, Object> arguments = ImmutableMap.of("type", repositoryConfigType.name());
+    Map<String, Object> arguments = ImmutableMap.of("type", type, "op", op);
```
Comment (adutra) [inline servers/quarkus-auth/src/main/java/org/projectnessie/server/authz/CelBatchAccessChecker.java:120]: That came as a surprise to me BTW: the `op` argument was missing, which makes the default rule for viewing refs fail. I think it's a bug.

File: servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java (hunk 1 above)
Comment (adutra) [reply servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: OTOH, it seems that `getIdentifiedKeys` is only used in `logEntryOperationsAccessCheck`, so I think we can make it behave the way we want without introducing regressions.

Comment (dimas-b) [reply servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: Missing delete tests might be an oversight :thinking: I think if we can recover deleted IDs in that method, we should :)

Comment (adutra) [reply servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: I changed `VersionStore` as you suggested. I kept the changes in this method just in case. Does that sound OK to you?

Comment (dimas-b) [reply servers/services/src/main/java/org/projectnessie/services/impl/TreeApiImpl.java:520]: Yeah, keeping this change looks reasonable to me :+1:

**Review by dimas-b — APPROVED** [review]
LGTM :+1: Thanks @adutra !
