### PR TITLE
Properly return `ParamConverterProvider` errors as HTTP/400

### LINKED ISSUE #6333: Invalid refrence type specification in REST API leads to 500 responses instead of 400
```
Request method:	DELETE
Request URI:	http://localhost:38481/v2/trees/test%402e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d?type=X
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Headers:		Accept=application/json, application/javascript, text/javascript, text/json
				Content-Type=application/json
Cookies:		<none>
Multiparts:		<none>
Body:			<none>

HTTP/1.1 500 Internal Server Error
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Type: application/json
Connection: close
Content-Length: 236

{
    "status": 500,
    "reason": "Internal Server Error",
    "message": "org.glassfish.jersey.server.ParamException$QueryParamException: HTTP 404 Not Found, caused byjava.lang.IllegalArgumentException: No enum constant org.projectnessie.model.Reference.ReferenceType.X",
    "errorCode": "UNKNOWN",
    "serverStackTrace": null
}
```

This is clearly a user error - the response should have a 4xx status code instead,

### PR DESCRIPTION
**Pull request by snazy**
Fixes #6333

### CODE REVIEW

File: servers/rest-services/src/main/java/org/projectnessie/services/restjakarta/NessieExceptionMapper.java [hunk 1]
```diff
@@ -82,13 +83,18 @@ public Response toResponse(Exception exception) {
     } else if (exception instanceof NotSupportedException) {
       errorCode = ErrorCode.UNSUPPORTED_MEDIA_TYPE;
       message = exception.getMessage();
+    } else if (exception instanceof WebApplicationException
```
Comment (snazy) [inline servers/rest-services/src/main/java/org/projectnessie/services/restjakarta/NessieExceptionMapper.java:86]: Sadly a "complicated" condition here, so it works with both Quarkus (RESTeasy) and Jersey.
Didn't want to have different code paths for javax + jakarta.

**Review by dimas-b — APPROVED** [review]
Thanks for the quick fix, @snazy ! :+1:
