### PR TITLE
Remove @Startup init from NessieHttpAuthenticator

### LINKED ISSUE #1868: CI flaky since #1777
CI for PRs + Ci for main are flaky.

From CI logs (in `:nessie-quarkus`):
```
Error:  Errors: 
Error:    TestBasicAuthentication.testValidAdminCredentials:43 » NessieInternalServer In...
Error:    TestBasicAuthentication.testValidCredentials:36 » NessieInternalServer Interna...
```

The preceding errors point to some internal error, probably related to Quarkus' test-profile w/ OIDC issue.

### PR DESCRIPTION
**Pull request by dimas-b**
Fixes #1868

---
This change is [Reviewable](https://reviewable.io/reviews/projectnessie/nessie/1871)

### CODE REVIEW

File: servers/quarkus-server/src/main/java/org/projectnessie/server/authn/NessieHttpAuthenticator.java [hunk 1]
```diff
@@ -46,7 +45,6 @@
 @Alternative // @Alternative + @Priority ensure the original HttpAuthenticator bean is not used
 @Priority(1)
 @ApplicationScoped
-@Startup // Initialize and load config on the main thread rather than on event loop threads
```
Comment (dimas-b) [inline servers/quarkus-server/src/main/java/org/projectnessie/server/authn/NessieHttpAuthenticator.java:49]: I added this initially to workaround the context class loader problem that were later mitigated by running each test class in a separate JVM. So, forcing startup init is no longer required.

I suspect forcing startup init might interfere with how Quarkus handles security providers. The startup process involves a set/get round trip though a variable in `ElytronSecurityDomainManager`, which is in turn driven by generated code. ATM I'm not sure what the sequence of actions is or even whether it is stable on each run.

Let's go back to on-demand init for the authenticator, which is what Quarkus does for its default `HttpAuthenticator`.

**Review by rymurr — APPROVED** [review]

**Review by snazy — APPROVED** [review]
