### PR TITLE
Java 11 HttpClient

### LINKED ISSUE #4448: Replace `URLConnection` with Java's `HttpClient` when Java 8's no longer supported
The implementation of `HttpURLConnection` is quite old and does not always conform to current internet standards.
Java's new HTTP client implementation, which is available since Java 11, is fine.

Since this change requires Java 11, this can only be done when compatibility with Java 8 can be removed.

* [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html)
* [Discussion on net-dev mailing list](https://mail.openjdk.java.net/pipermail/net-dev/2022-June/018417.html)
* [HttpURLConnection source](https://github.com/openjdk/jdk/blame/e01cd7c3ed923cd19509fc972ba6e4aa2991289f/src/java.base/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L982-L983)
* [Nessie PR with relevant discussion](https://github.com/projectnessie/nessie/pull/4429)

### LINKED ISSUE #4774: `ClassCastException` when initializing HDFS-Spark
Some Hadoop libraries (HDFS stuff?) seem to "tweak" Java's mechanism to resolve URLs, so instead of resolving `http` to `HttpURLConnection`, it is resolved fo `org.apache.hadoop.fs.FsUrlConnection`, which leads to a `ClassCastException`.

The integration test in question is one that pulls in Spark, Flink, Presto, Iceberg and, of course, Nessie.

Not sure whether we have to tweak the Nessie client here to make it "resistant" against such things.

Frankly, our expectation that the cast-operation in question will always resolve to a `HttpURLConnection` is not great either.

Two issues at play here:
1. Hadoop code "hijacks" `http`, which feels wrong (there are implementations of `java.net.URLStreamHandler` in Hadoop code)
2. Nessie always expects the result of `URL.openConnection()` to be an instance of `java.net.HttpURLConnection`, which is strictly speaking wrong as well.

Since we cannot tweak (old and released) Hadoop code, the only solution here is to change the Nessie client code.

```
URI uri;
HttpURLConnection con = (HttpURLConnection) uri.toURL().openConnection();
```

```
java.lang.ClassCastException: class org.apache.hadoop.fs.FsUrlConnection cannot be cast to class java.net.HttpURLConnection (org.apache.hadoop.fs.FsUrlConnection is in unnamed module of loader 'app'; java.net.HttpURLConnection is in module java.base of loader 'bootstrap')
	at org.projectnessie.client.http.HttpRequest.executeRequest(HttpRequest.java:90)
	at org.projectnessie.client.http.HttpRequest.get(HttpRequest.java:188)
	at org.projectnessie.client.http.HttpTreeClient.getReferenceByName(HttpTreeClient.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.projectnessie.client.http.NessieHttpClient$ExceptionRewriter.invoke(NessieHttpClient.java:161)
	at com.sun.proxy.$Proxy18.getReferenceByName(Unknown Source)
	at org.projectnessie.client.http.v1api.HttpGetReference.get(HttpGetReference.java:47)
	at org.apache.iceberg.nessie.NessieIcebergClient.loadReference(NessieIcebergClient.java:100)
	at org.apache.iceberg.nessie.NessieIcebergClient.lambda$new$0(NessieIcebergClient.java:74)
	at org.apache.iceberg.relocated.com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.apache.iceberg.nessie.NessieIcebergClient.getRef(NessieIcebergClient.java:82)
	at org.apache.iceberg.nessie.NessieIcebergClient.refresh(NessieIcebergClient.java:86)
	at org.apache.iceberg.nessie.NessieTableOperations.doRefresh(NessieTableOperations.java:110)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:96)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:79)
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:44)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:161)
	at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:556)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:143)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:100)
	at org.apache.spark.sql.connector.catalog.TableCatalog.tableExists(TableCatalog.java:156)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:622)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)
	at org.projectnessie.integtests.crossengine.ITCrossEngine.createTables(ITCrossEngine.java:48)

```

### PR DESCRIPTION
**Pull request by snazy**
Adds support for the new HTTP client introduced in Java 11. By
default, Nessie clients use the new HTTP client instead of the
legacy `URLConnection` based client.

The legacy client has a couple of disadvantages:
* It has to "unconditionally" cast the `URLConnection` to a
  `HttpURLConnection`, which can lead to issues when running
  HDFS/spark as documented in #4774.
* `HttpURLConnection` implements redirection inconsistently, see
  #4429.
* `URLConnection` is a general purpose API based on `java.net.URL`
  and will get no new features (like SNI or HTTP/2), likely only
  gets serious bug fixes. Therefore its use is no longer
  recommended.

Java's new HTTP client is based on Java's `Flow` API (reactive).
It offers support for a bunch of interesting features like HTTP/2,
`SSLParameters` and SNI (hostname verification).

Test changes:
* Test code infrastructure to setup SSL has been changed and
  made reusable.
* Tests exercising combinations of SSL yes/no + HTTP/2 yes/no have
  been added.

Notes on http backends: #5285 changed the "dummy" HTTP server used
for tests in the `nessie-client` project from
`com.sun.net.httpserver.HttpServer` to Jetty, which was fine at that
time. However, during the development of this PR it was discovered
that all currently maintained Jetty versions have a bug. The test
`o.p.client.http.TestHttpClient#testWriteWithVariousSizes` performs
a couple of requests that share the same Jave `HttpClient` instance.
On "limited" machines, like GitHub's hosted runners, it can somewhat
consistently happen that one request has technically finished (the
response has been fully processed by the client) but is still in
its, say, "cleanup" phase, where Jetty performs some cleanup
actions. One of these actions is a check whether all data has been
consumed, [here](https://github.com/eclipse/jetty.project/blob/2b817f06c64a26003cdbaa25a3769c1c8b9178cf/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConnection.java#L465-L469).

If the client sends data for the "next" request quick enough, before
Jetty reaches the `_generator.isPersistent() && !complete` check,
that check will abort the processing and eventually close the
connection. Closing the connection causes either `EOFException`s or
`IOException`s for a TCP conneciton reset. This bug did not happen
with Nessie's legacy `URLConnection` based client nor does it happen
with Apache's HTTP client. The fact that the bug was only
reproducible on GitHub hosted runners made it pretty difficult, as
reading unfamiliar 3rd party debug/trace logs (Java's new HTTP
client + Jetty) and figuring out what exactly in the ocean of log
messages gives a clue what happens but foremost _why_ it happens.

Due to the Jetty bug described above, this PR also exchanges the
Jetty server with Undertow for the tests in the `nessie-client`
project. Undertow supports HTTP/2, which Jetty doesn't, so
tests can also exercise the HTTP/2 functionality of the new HTTP
client.

For the interested audience: Extensive logging can be enabled with:
* `systemProperty("jdk.internal.httpclient.debug", "true")` +
  `systemProperty("jdk.httpclient.HttpClient.log", "all")`
* Running the `:nessie-client:test` tasks with
  `-Dtest.log.level=TRACE`

And a friendly "hi" to the Quarkus project: The `ClassLoader` set in
`o.p..client.http.impl.jdk11.JavaRequest.Submitter#cl` is only there
to make tests pass in the Quarkus test framework.

Fixes #4774
Fixes #4448

### CODE REVIEW

File: clients/client/src/main/java/org/projectnessie/client/http/impl/RequestContextImpl.java [hunk 1]
```diff
@@ -99,4 +99,9 @@ public void addResponseCallback(BiConsumer<ResponseContext, Exception> responseC
   public List<BiConsumer<ResponseContext, Exception>> getResponseCallbacks() {
     return responseCallbacks;
   }
+
+  @Override
+  public String toString() {
+    return method.toString() + " to " + uri;
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/RequestContextImpl.java:105]: nit: Do we really need `to`?.. `POST http://nessie/api/v1/...` would look nicer IMHO :)

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java [hunk 2]
```diff
@@ -0,0 +1,431 @@
...
+      JavaResponseContext responseContext = new JavaResponseContext(response);
+
+      List<BiConsumer<ResponseContext, Exception>> callbacks = context.getResponseCallbacks();
+      if (callbacks != null) {
+        callbacks.forEach(callback -> callback.accept(responseContext, null));
+      }
+
+      config.getResponseFilters().forEach(responseFilter -> responseFilter.filter(responseContext));
+
+      if (response.statusCode() >= 400) {
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:130]: Should we have this logic in `UrlConnectionRequest` too?

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java [hunk 3]
```diff
@@ -0,0 +1,431 @@
...
+      }
+    }
+  }
+
+  /**
+   * Executor used to serialize the response object to JSON.
+   *
+   * <p>Java's new {@link HttpClient} uses the {@link Flow.Publisher}/{@link Flow.Subscriber}/{@link
+   * Flow.Subscription} mechanism to write and read request and response data. We have to use that
+   * protocol. Since none of the implementations must not block, writes and reads run in a separate
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:159]: `none` -> `all`?

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java [hunk 4]
```diff
@@ -0,0 +1,431 @@
...
+   * pool.
+   *
+   * <p>Jackson has no "reactive" serialization mechanism, which means that we have to provide a
+   * custom {@link OutputStream}, which delegates {@link Flow.Subscriber#onNext(Object) writes} to
+   * the subscribing code.
+   */
+  private static final Executor writerPool =
+      new ForkJoinPool(Math.max(8, ForkJoinPool.getCommonPoolParallelism()));
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:167]: Make the `8` configurable just in case?

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java [hunk 5]
```diff
@@ -0,0 +1,431 @@
...
+   */
+  private final class Submitter extends OutputStream
+      implements Flow.Publisher<ByteBuffer>, Runnable, Flow.Subscription {
+
+    // Okay - this is weird - but it is necessary when running tests with Quarkus via
+    // `./gradlew :nessie-quarkus:test`.
+    private final ClassLoader cl = Thread.currentThread().getContextClassLoader();
+    private final RequestContext context;
+    private final AtomicBoolean subscribed = new AtomicBoolean();
+    private final AtomicLong demand = new AtomicLong();
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:199]: Could we reuse `BodyPublishers.ofInputStream()` and set up a `java.nio.channels.Pipe` between Jackson output and HTTP input streams? I suppose it might be simpler in code and will probably provide similar runtime behaviour?

File: clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java [hunk 6]
```diff
@@ -61,28 +73,88 @@ public class TestHttpClient {
...
-    return get(address, 15000, 15000, disableCompression);
+  private HttpClient createClient(URI baseUri, Consumer<HttpClient.Builder> customizer) {
+    HttpClient.Builder b =
+        HttpClient.builder()
+            .setBaseUri(baseUri)
+            .setObjectMapper(MAPPER)
+            .setConnectionTimeoutMillis(15000)
+            .setReadTimeoutMillis(15000);
+    customizer.accept(b);
+    return b.build();
```
Comment (dimas-b) [inline clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java:88]: Do we have tests for `UrlConnectionClient`?

**Review by dimas-b — COMMENTED** [review]
LGTM overall. My only real concern is the custom `Flow` code. Please see my alternative suggestion in a separate commit. If you think a custom `Flow` is still necessary, I'll have to take more time to review it :) but I hope we can construct a similar pipeline using existing utils.

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 4 above)
Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:167]: Better not. It's there to allow _at least_ 8 concurrent request serializations on tiny machines - that's already a lot.

File: clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java (hunk 6 above)
Comment (snazy) [reply clients/client/src/test/java/org/projectnessie/client/http/TestHttpClient.java:88]: The build-script has a bunch of configurations, yes.

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 2 above)
Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:130]: Duh - this code is actually superfluous, removed. (`NessieHttpResponseFilter`)

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 5 above)
Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java]: Sorry, I'm confused... "unrelated issues" still prevented that approach? I'm just curious why it did not work :)

Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java]: Oh, I see you changed to `BodyPublishers.ofInputStream`... will re-review soon (hopefully)

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 4 above)
Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:187]: fair enough

File: clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java [hunk 7]
```diff
@@ -137,11 +164,37 @@ public HttpClient build() {
...
+
+      static {
+        Function<HttpRuntimeConfig, HttpClient> factory;
+        try {
+          Class.forName("java.net.http.HttpClient");
+          factory =
+              config ->
+                  // Need the system property for tests, "normal" users can use standard
+                  // configuration options.
+                  Boolean.getBoolean("nessie.client.force-url-connection-client")
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java:189]: nit: I see tests run under Java8 to exercise `UrlConnectionClient`, but I did not find any references to this system property :thinking:

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java [hunk 8]
```diff
@@ -0,0 +1,204 @@
...
+    return BodyPublishers.ofInputStream(
+        () -> {
+          try {
+            Pipe pipe = Pipe.open();
+            writerPool.execute(
+                () -> {
+                  try {
+                    // Okay - this is weird - but it is necessary when running tests with Quarkus
+                    // via `./gradlew :nessie-quarkus:test`.
+                    Thread.currentThread().setContextClassLoader(cl);
```
Comment (dimas-b) [inline clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:160]: Not really weird, but quite normal IMO :)

I think it'd be nice to reset the TCCL back to its original value, though.

Also, from the correctness perspective, I do think that the value of `cl` should be `body.getClass().getClassLoader()`... so it might be worth moving the TCCL logic into `writeToOutputStream`. WDYT?

**Review by dimas-b — COMMENTED** [review]
`Pipe`-based writing looks pretty solid to me :)

Still a couple of new minor comments.

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 8 above)
Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:160]: On the second though, I think it's correct to propagate current TCCL (i.e. from line 150), but I think we should still reset TCCL on the executor thread back to its original value.

File: clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java (hunk 7 above)
Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java:189]: Yep. It's only there as a "last resort fallback".

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 8 above)
Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:160]: Nope. Needs to be the CL from the current thread - it's kinda weird, but makes sense (class loader loading the class !== class loader required for tests).

Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:160]: On the third though :) perhaps should should use TCCL of `JavaRequest.class.getClassLoader()`.

We expect to serialize only Nessie model classes, which are already a dependency of the client code. At the same time we cannot be certain that the calling thread has the right TCCL in all cases because the thread is normally owned by engines. Also, `body.getClass().getClassLoader()` will not work it it's a `List` or model classes, for example.

File: clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java (hunk 7 above)
Comment (dimas-b) [reply clients/client/src/main/java/org/projectnessie/client/http/HttpClient.java:189]: ok

File: clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java (hunk 8 above)
Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:161]: > On the third thought :) perhaps we should use TCCL of `JavaRequest.class.getClassLoader()`.

That doesn't work

Comment (snazy) [reply clients/client/src/main/java/org/projectnessie/client/http/impl/jdk11/JavaRequest.java:161]: It's not a question of the "depencency" - the thread's current class loader is the one that loads needed classes.
(Tried JavaRequest + some model class - neither works)

**Review by dimas-b — APPROVED** [review]
