### PR TITLE
Use unsaved in-memory commits during key list re-construction

### LINKED ISSUE #3466: Merge fails if more than 20 commits are present on the source branch
* Start Nessie server with `quarkus:dev`
* Create a new branch `test1`
* Start a local Spark (1 node is sufficient)
* Make more that 20 commits in `test1`
* Attempt to merge `test1` to the default branch
* Observe an error similar to the following:
```
[...]
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.175 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.163 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.165 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.184 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.143 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.138 seconds
spark-sql> insert into t2 (id, data) values (1, 'a');
Time taken: 0.191 seconds
```
```
$ nessie  merge test1 -c 2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d
Client Error Not Found: Commit '2b2a3501e5c50ce7b5ba562d4a932c0f9509d08ab019953c89ec9491e0b1dea6' not found (Status code: 404)
Requested URL: http://localhost:19120/api/v1/trees/branch/main/merge?expectedHash=2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d
Server status: 404
Error code: REFERENCE_NOT_FOUND
Server message: Commit '2b2a3501e5c50ce7b5ba562d4a932c0f9509d08ab019953c89ec9491e0b1dea6' not found
Server traceback: None
```
Note: the hash from the error message is not visible in Nessie commit logs in CLI.
Note: the hash from the merge error is different in each new merge attempt without making any other commits.

### PR DESCRIPTION
**Pull request by dimas-b**
* Allow the unsaved in-memory commits built during merge / transplant
  operations to be found during key list re-construction.

* Skip the in-memory lookup in the common case of non-merge call
  paths to reduce the amount of transient lists (parameters and
  results).

* Parameterize merge / transplant test cases for full coverage
  of related code.

Fixes #3466

### CODE REVIEW

File: versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java [hunk 1]
```diff
@@ -635,23 +636,77 @@ protected void validateHashExists(OP_CONTEXT ctx, Hash hash) throws ReferenceNot
    */
   protected abstract List<CommitLogEntry> fetchPageFromCommitLog(OP_CONTEXT ctx, List<Hash> hashes);
 
+  private List<CommitLogEntry> fetchPageFromCommitLog(
```
Comment (snazy) [inline versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java:639]: Mind renaming this to `fetchMultipleFromCommitLog`? I think, the term "page" is wrong here (and actually always was - it was just used to fetch a whole page).

Comment (dimas-b) [reply versioned/persist/adapter/src/main/java/org/projectnessie/versioned/persist/adapter/spi/AbstractDatabaseAdapter.java]: renamed (in a separate commit for ease of review)

**Review by snazy — APPROVED** [review]

File: versioned/persist/tests/src/main/java/org/projectnessie/versioned/persist/tests/AbstractMergeTransplant.java [hunk 2]
```diff
@@ -148,14 +168,15 @@ void apply(
...
+  private Hash[] mergeTransplant(int numCommits, MergeOrTransplant mergeOrTransplant)
+      throws Exception {
     BranchName main = BranchName.of("main");
     BranchName branch = BranchName.of("branch");
     BranchName conflict = BranchName.of("conflict");
 
     databaseAdapter.create(branch, databaseAdapter.hashOnReference(main, Optional.empty()));
 
-    Hash[] commits = new Hash[3];
+    Hash[] commits = new Hash[numCommits];
```
Comment (ajantha-bhat) [inline versioned/persist/tests/src/main/java/org/projectnessie/versioned/persist/tests/AbstractMergeTransplant.java:179]: I remember that my PR for same issue got blocked because there was no strict validation. But this PR also don't have any validation but went ahead. 
I am not sure what is the process here.

Comment (snazy) [reply versioned/persist/tests/src/main/java/org/projectnessie/versioned/persist/tests/AbstractMergeTransplant.java:179]: Your change was complex and changed the algorithm/implementation to generate the key-lists.
Dmitri's change did not change that algorithm.

Comment (dimas-b) [reply versioned/persist/tests/src/main/java/org/projectnessie/versioned/persist/tests/AbstractMergeTransplant.java:179]: I also checked code coverage in IntelliJ (manually) - all branches in the new `if` statements were covered :)
