### PR TITLE
Load correct view metadata for a given ref

### LINKED ISSUE #3734: The load and loadDefinition for NessieViewCatalog always return latest view info
**What happened**:
The loadDefinition and load in NessieViewCatalog return unexpected results in some cases.

**What you expected to happen**:
When I call loadDefinition or load a view, I should not always get the info of the latest view.
The NessieViewCatalog should fetch the version and return the expected version.

**How to reproduce it (as minimally and precisely as possible)**:
Create branch A and create view V1 on it.
Create branch B from branch A and update view V1 on branch B  to V2.
When I call loadDefinition or load the view V2 on branch B, I will get the correct results.
When I call loadDefinition or load the view V1 on branch A, I will get the same result as V2.

**Details**:
- Nessie server type (docker/built from source) and version:
Build from source. 0.22
- Client type (Ex: UI/Spark/pynessie ...) and version:
NessieViewCatalog

### PR DESCRIPTION
**Pull request by nastra**
This makes sure that we load the correct view metadata when specifying a
particular reference.

fixes #3734

### CODE REVIEW

**Review by snazy — COMMENTED** [review]
Is this basically changed to what we do for Tables in Iceberg for Nessie?

**Comment by nastra** [comment]
@snazy yes

**Review by dimas-b — APPROVED** [review]

File: clients/iceberg-views/src/main/java/org/apache/iceberg/nessie/NessieViewOperations.java [hunk 1]
```diff
@@ -26,7 +29,11 @@
 import org.apache.iceberg.io.FileIO;
 import org.apache.iceberg.util.Tasks;
 import org.apache.iceberg.view.BaseMetastoreViewOperations;
+import org.apache.iceberg.view.BaseVersion;
+import org.apache.iceberg.view.HistoryEntry;
+import org.apache.iceberg.view.Version;
```
Comment (dimas-b) [inline clients/iceberg-views/src/main/java/org/apache/iceberg/nessie/NessieViewOperations.java:34]: Does this mean we have a circular dependency with Iceberg?

Comment (nastra) [reply clients/iceberg-views/src/main/java/org/apache/iceberg/nessie/NessieViewOperations.java:34]: yes but the code here will move eventually into iceberg
