### PR TITLE
Extract `CommitMetaUpdater` class, fix "set authors on merge"

### LINKED ISSUE #6956: Merging branches doesn't show any author name
While trying to merge a branch "branchdemo" into "main", it seems there is no default author name added (not being sent as response)

**What happened**:
Tried to merge a branch into main using the below API and request payload:
POST `trees/main%4058346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25/history/merge`

`{"fromRefName":"branchdemo","fromHash":"621f99726e4263a32eedf80c2270c739054407adf0e4759518fb61670465b3f7"}`

Response:
```
{
    "wasApplied": true,
    "wasSuccessful": true,
    "resultantTargetHash": "521c292e2b39a032fdd57c421d488120b90741c6560e9cebf470fbbb73d13ad2",
    "commonAncestor": "1b91af97348ae86e388e355c144409279bca48698454d8fcda4e197e09aac251",
    "targetBranch": "main",
    "effectiveTargetHash": "58346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25",
    "expectedHash": "58346f07f41dd2033082cec7be5311010b1644febb19c016777a44c4752cac25",
    "details": []
}
```

**What you expected to happen**:
Response should contain the author name (defaulted to original user probably)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a common commit before creating a branch from main
2. Create a branch from main
3. Create a commit in branch (make sure that it has authorname passed to API) 
4. Merge the branch into main

**Details**:
- Nessie server type (docker/built from source) and version: 0.60.1
- Client type (Ex: UI/Spark/pynessie ...) and version:

### PR DESCRIPTION
**Pull request by snazy**
... and add some tests

Fixes #6956

### CODE REVIEW

File: servers/services/src/testFixtures/java/org/projectnessie/services/impl/AbstractTestPrincipals.java [hunk 1]
```diff
@@ -111,7 +111,7 @@ public void committerAndAuthorMerge() throws Exception {
             CommitMeta::getHash)
         .containsExactly(
             "NessieHerself",
-            "NessieHerself",
+            "ThatNessieGuy",
```
Comment (snazy) [inline servers/services/src/testFixtures/java/org/projectnessie/services/impl/AbstractTestPrincipals.java:114]: Adopted to "updated behavior for set-authors"

**Review by dimas-b — APPROVED** [review]

**Comment by snazy** [comment]
Note: the "pull information from merged commits" clashes with #7035 / #4562, because that will support merging "heavily nested trees" and identifying the "merged commits" would become extremely difficult. Therefore the new storage model will _only_ set the author to the committer.
