### PR TITLE
Fix nessie catalog check for delta

### LINKED ISSUE #3552: Delta tests and docs dont use `NessieSparkSessionExtensions`
in the delta demo we are using the SQL nessie extensions:
https://github.com/projectnessie/nessie-demos/blame/099cb4a0b1e8a92e456770edeb909bcb4e1b1e7a/notebooks/nessie-delta-demo-nba.ipynb#L61

however in our delta tests and docs we do not.

Delta tests configuration:
https://github.com/projectnessie/nessie/blob/d36e031431f694ee83de6a7877c0417ad79ef94f/clients/deltalake/src/test/java/org/projectnessie/deltalake/AbstractDeltaTest.java#L99-L103

delta spark docs:
https://github.com/projectnessie/nessie/blame/dcd1406a4ebc95e46fd65c83b5bb6a4efe04a966/site/docs/tools/deltalake/spark.md#L43-L44

both should be changed to show and test all of the capabilities in a delta context.

### PR DESCRIPTION
**Pull request by XN137**
Follow-up to https://github.com/projectnessie/nessie/pull/3557

Fixes #3552

Original problem:
After https://github.com/projectnessie/nessie/pull/2377 the nessie spark sql extensions could no longer be used with delta.

Also updates the deltalake spark docs removing "spark 2" references and adding info about the nessie spark sql extenions.

### CODE REVIEW

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala [hunk 1]
```diff
@@ -164,22 +164,30 @@ object NessieUtils {
...
+        case Some(clazz) => s"but $catalogName is a $clazz"
+        case None =>
+          s"but spark.sql.catalog.$catalogName.catalog-impl is not set"
+      }
+      // Referring to https://github.com/apache/iceberg/blob/master/nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
+      // Not using fully-qualified class name to provide protection from shading activities (if any)
+      require(
+        catalogImpl
+          .exists(impl => impl.endsWith(".NessieCatalog")),
+        s"The command works only when the catalog is a NessieCatalog ($catalogErrorDetail). Either set the catalog via USE <catalog_name> or provide the catalog during execution: <command> IN <catalog_name>."
```
Comment (XN137) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala:187]: Note that we have tests to make sure this still works in the iceberg case:
https://github.com/projectnessie/nessie/blob/8ba7079c54325c90e39ebf4e234c014711ca0e8e/clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java#L703-L721

I could not use the same style of testing for delta because i didnt know which non-delta catalog to use (no iceberg jar on classpath).

**Review by nastra — APPROVED** [review]

**Comment by XN137** [comment]
tests are passing but codecov is reporting decreased coverage on untouched files... so I will just ignore that check
