### PR TITLE
Fix Device Code flow tests with Java 21

### LINKED ISSUE #7918: `ITOAuth2Client` consistently failing locally
### Issue description

`./gradlew intTest`

```
> Task :nessie-client:intTest

ITOAuth2Client > testOAuth2ClientInitialRefreshToken(GrantType) > [4] initialGrantType=DEVICE_CODE FAILED
    java.lang.RuntimeException at ITOAuth2Client.java:181
        Caused by: java.lang.NullPointerException at JavaHttpClient.java:68

ITOAuth2Client > testOAuth2ClientDeviceCodeAccessDenied() FAILED
    java.lang.AssertionError at ITOAuth2Client.java:321

```

### PR DESCRIPTION
**Pull request by adutra**
Fixes #7918.

### CODE REVIEW

File: api/client/src/main/java/org/projectnessie/client/auth/oauth2/DeviceCodeFlow.java [hunk 1]
```diff
@@ -194,19 +194,11 @@ private void pollForNewTokens(String deviceCode) {
                   TimeUnit.MILLISECONDS);
           return;
         case "access_denied":
-          LOGGER.error(MSG_PREFIX + "Authorization denied by user");
```
Comment (adutra) [inline api/client/src/main/java/org/projectnessie/client/auth/oauth2/DeviceCodeFlow.java:197]: Too much noise in the logs.

File: api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java [hunk 2]
```diff
@@ -213,11 +216,13 @@ private void triggerDeviceCodeFlow(URL initialUrl, String userCode) {
     try {
       LOGGER.info("Starting device code flow.");
       Set<String> cookies = new HashSet<>();
-      URL loginPageUrl = enterUserCode(initialUrl, userCode, cookies);
+      HttpURLConnection codeActionConn = enterUserCode(initialUrl, userCode, cookies);
```
Comment (dimas-b) [inline api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java:219]: Should we close this connection when done?

Comment (adutra) [reply api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java:219]: `HttpURLConnection` is not closeable. What "closes" the request is when a terminal action is invoked, e.g. `getResponseCode()`.

Comment (dimas-b) [reply api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java:219]: :facepalm:

Comment (dimas-b) [reply api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java:219]: `disconnect()` maybe?... although for lightly used test code it's probably fine to ignore.

Comment (adutra) [reply api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java]: Frankly I don't think it will make any difference here, but why not.

Comment (dimas-b) [reply api/client/src/testFixtures/java/org/projectnessie/client/auth/oauth2/ResourceOwnerEmulator.java]: thx!
