### PR TITLE
Fix potential class-loader deadlock via `Namespace.EMPTY`

### LINKED ISSUE #8961: Possible class loader deadlock in `Namespace`
`org.projectnessie.model.Namespace#EMPTY` references subclass `ImmutableNamespace`, which can lead to a class loader deadlock.

### PR DESCRIPTION
**Pull request by snazy**
Fixes #8961

### CODE REVIEW

File: api/model/src/main/java/org/projectnessie/model/NessieConstants.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.projectnessie.model;
+
+/** Utility class holding some constants, mostly to prevent potential class loader deadlocks. */
+public final class NessieConstants {
+  public static final Namespace EMPTY_NAMESPACE = Namespace.builder().build();
```
Comment (dimas-b) [inline api/model/src/main/java/org/projectnessie/model/NessieConstants.java:20]: This could probably be in a `static` inner class in `Namespace`... or do you prefer a separate class?

Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/NessieConstants.java:20]: That would not solve the issue, right?

Comment (dimas-b) [reply api/model/src/main/java/org/projectnessie/model/NessieConstants.java:20]: But it would. A `static` inner class is mostly equivalent to a top-level class (no extra loading dependencies), except it's namespaced under the outer class.

Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/NessieConstants.java]: That's not much different then. I thought you wanted to propose class-loading-lazy initialization from a static method in Namespace.

File: api/model/src/main/java/org/projectnessie/model/Namespace.java [hunk 2]
```diff
@@ -48,6 +49,18 @@ public abstract class Namespace extends Content {
...
+
+    public static final Namespace EMPTY_NAMESPACE = builder().build();
+  }
+
+  /**
+   * Refactor all code references to this constant to use {@link Empty#EMPTY_NAMESPACE}, there's a
+   * non-zero risk of causing a class loader deadlock.
+   */
+  @Deprecated
   public static final Namespace EMPTY = builder().elements(Collections.emptyList()).build();
```
Comment (dimas-b) [inline api/model/src/main/java/org/projectnessie/model/Namespace.java:64]: One more nittish comment, but this is public API, so I hope it might be cleaner for outside callers:

We could probably have in `Namespace`:
```
public static Namespace emptyNamespace() {
   return Empty.EMPTY_NAMESPACE;
}
```
... then `Empty` can be `private`... WDYT?

Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/Namespace.java:64]: Nah - let's keep it as is

**Review by dimas-b — APPROVED** [review]
