### PR TITLE
Let SQL `CREATE` and `ASSIGN` use `USE`d ref

### LINKED ISSUE #4685: SQL Extension CREATE TAG does not "honour" USE REFERENCE
**What happened**:
On a spark session after `USE REFERENCE develop` (i.e. we "checkout" the `develop` branch) when a `CREATE TAG tagName` is issued the tag is created on the head of the default branch (usually `main`).

**What you expected to happen**:
I would've expected the tag created from the HEAD of the `develop` branch.

**How to reproduce it (as minimally and precisely as possible)**:
TBD.

**Details**:
- Nessie server type (docker/built from source) and version: 0.30.0 docker
- Client type (Ex: UI/Spark/pynessie ...) and version: Spark

### PR DESCRIPTION
**Pull request by snazy**
The current behavior of `CREATE BRANCH|TAG` is to fall back to the
default branch, if the `FROM` clause is omitted.
The current behavior of `ASSIGN BRANCH|TAG` is to fall back to the
default branch, if the `TO` clause is omitted.

As outlined in #4685, the above behavior is not intuitive.

The PR changes the above behaviors to fall back to the name of the
reference configured for the Spark session, honoring a `USE`
statement issued by the user.

Fixes #4685

### CODE REVIEW

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseAssignReferenceExec.scala [hunk 1]
```diff
@@ -34,30 +34,37 @@ abstract class BaseAssignReferenceExec(
...
   ): Seq[InternalRow] = {
-    val toRef = toRefName
-      .map(r => api.getReference().refName(r).get())
-      .getOrElse(api.getDefaultBranch)
-    val hash = api.getReference().refName(branch).get().getHash
+    val currentHash = api.getReference().refName(refNameToAssign).get().getHash
+
+    val toRef =
+      if (toRefName.isDefined) api.getReference.refName(toRefName.get).get()
+      else NessieUtils.getCurrentRef(api, currentCatalog, catalog)
```
Comment (snazy) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseAssignReferenceExec.scala:41]: This is the actual change, the other changes are cleanups.

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala [hunk 2]
```diff
@@ -35,10 +38,20 @@ abstract class BaseCreateReferenceExec(
...
-    val sourceRef = createdFrom
-      .map(x => api.getReference.refName(x).get)
-      .orElse(Option(api.getDefaultBranch))
-      .orNull
+    val sourceRef =
+      if (createdFrom.isDefined) {
+        api.getReference.refName(createdFrom.get).get()
+      } else {
+        try {
+          NessieUtils.getCurrentRef(api, currentCatalog, catalog)
```
Comment (snazy) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala:46]: This is the actual change, the other changes are cleanups.

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala [hunk 3]
```diff
@@ -238,20 +238,32 @@ object NessieUtils {
   }
 
   def getCurrentRef(
+      api: NessieApiV1,
```
Comment (snazy) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala:241]: No need to create a new api instance, because all call sites have one available.

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala [hunk 4]
```diff
@@ -238,20 +238,32 @@ object NessieUtils {
...
-    val api = nessieAPI(currentCatalog, catalog)
+    val refName = getCurrentRefName(currentCatalog, catalog)
     try {
       api.getReference.refName(refName).get
-    } finally {
-      api.close()
+    } catch {
+      case e: NessieNotFoundException =>
+        throw new NessieNotFoundException(
+          s"Could not find current reference $refName configured in spark configuration for catalog '${catalog
```
Comment (snazy) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/NessieUtils.scala:251]: Nicer error message

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala [hunk 5]
```diff
@@ -35,10 +38,20 @@ abstract class BaseCreateReferenceExec(
...
+        } catch {
+          case e: NessieNotFoundException =>
+            throw new NessieNotFoundException(
+              s"${e.getMessage} Use 'CREATE ${if (isBranch) "BRANCH" else "TAG"} ... FROM <existing-reference-name>'.",
```
Comment (snazy) [inline clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala:50]: Tell users how to work around the error

File: clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java [hunk 6]
```diff
@@ -76,15 +78,22 @@ public abstract class AbstractSparkSqlTest {
...
-  private String initialHashOfDefaultBranch;
+  private Branch initialDefaultBranch;
 
-  private final String refName = "testBranch";
+  private String refName;
   protected NessieApiV1 api;
 
   @BeforeEach
-  void setupSparkAndApi() throws NessieNotFoundException {
+  void setupSparkAndApi(TestInfo testInfo) throws NessieNotFoundException {
```
Comment (snazy) [inline clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:87]: Minor cleanups in this method, no functional change though

File: clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java [hunk 7]
```diff
@@ -109,12 +118,25 @@ void setupSparkAndApi() throws NessieNotFoundException {
...
+  }
+
+  private String defaultHash() {
+    return initialDefaultBranch.getHash();
   }
 
   @AfterEach
   void removeBranches() throws NessieConflictException, NessieNotFoundException {
+    // Reset potential "USE REFERENCE" statements from previous tests
+    SparkSession.active()
```
Comment (snazy) [inline clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:134]: This resets a `USE` issues in a test.

**Review by dimas-b — APPROVED** [review]

File: clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala (hunk 5 above)
Comment (snazy) [reply clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala:50]: This one is part of the actual "fix". It happens, when you've configured a default reference in the Spark-config that doesn't exist - but the user-facing error message is some generic "not found".
The case in line 41 happens when the user explicitly mentioned a "from" reference.

Comment (snazy) [reply clients/spark-extensions-base/src/main/scala/org/apache/spark/sql/execution/datasources/v2/BaseCreateReferenceExec.scala:50]: Oh, you're talking about `ASSIGN`... (me=blind) ... those should be clear with the change in `getCurrentRef`
