### PR TITLE
Ensure custom content-types work

### LINKED ISSUE #6591: Verify that adding new content types to Nessie works "everywhere"
Nessie internal code is built to support an extensible set of different content types. The (REST) API however is mostly not able to leverage "additional" content types or fails when those would be added (think: Java enum, current OpenAPI spec).

This issue is meant to ensure and empirically prove:
* adding new content types works on all levels (storage level serialization, model-API level serialization, REST-API level server & clients).
* add tests that validate this behavior

### PR DESCRIPTION
**Pull request by snazy**
* Add some more valdiations when registering content-type-bundles.
* Add a page on the project web site for registered content-types.
* Add tests in `:nessie-model` + `:nessie-versioned-spi` to verify that
  custom content-type-bundles and custom content-serializer-bundles
  work.

Fixes #6591

### CODE REVIEW

File: api/model/src/test/java/org/projectnessie/model/types/CustomTestContentTypeBundle.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ */
+package org.projectnessie.model.types;
+
+import org.projectnessie.model.types.ContentTypes.Registrar;
+
+public class CustomTestContentTypeBundle implements ContentTypeBundle {
+
+  @Override
+  public void register(Registrar registrar) {
+    registrar.register("TEST_CUSTOM_CONTENT_TYPE", CustomTestContent.class);
```
Comment (dimas-b) [inline api/model/src/test/java/org/projectnessie/model/types/CustomTestContentTypeBundle.java:24]: nit: use name constant from `CustomTestContent`?

File: api/model/src/test/java/org/projectnessie/model/types/CustomTestContentTypeBundle.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.projectnessie.model.types;
+
+import org.projectnessie.model.types.ContentTypes.Registrar;
+
+public class CustomTestContentTypeBundle implements ContentTypeBundle {
```
Comment (dimas-b) [inline api/model/src/test/java/org/projectnessie/model/types/CustomTestContentTypeBundle.java:20]: Suggestion: Do we really need the `ContentTypeBundle` interface? Why not load each custom type class via the service loader and then register them all automatically based on `@JsonTypeName` (which we validate to match the registered type name anyway)?

IIRC, service loader resources can list more than one service class per file.

With current approach it looks like type names leak across class boundaries without any good code-level reason :thinking: 

If that works, we might as well follow the same approach for `ContentSerializerBundle`, I guess.

Comment (snazy) [reply api/model/src/test/java/org/projectnessie/model/types/CustomTestContentTypeBundle.java:20]: In theory, yes.
But we need `Class<? extends Content>` for the registration. Service loaders however return instantiated instances of the class.

**Comment by snazy** [comment]
Updated the PR a bit.

* Introduced "top level" registry interfaces for content-type + content-serializer registration.
* Removed the `name` parameter

File: versioned/spi/src/main/java/org/projectnessie/versioned/store/ContentSerializerBundle.java [hunk 3]
```diff
@@ -15,9 +15,12 @@
...
-/** Implementations of this {@link java.util.ServiceLoader service} register content serializers. */
+/**
+ * Custom content serializers need to implement this interface and call {@link
+ * ContentSerializerRegistry#register(ContentSerializer)} for each serializer.
+ *
+ * <p>Instances of this class are loaded via Java's {@link java.util.ServiceLoader}.
+ */
 public interface ContentSerializerBundle {
-  void register(Consumer<ContentSerializer<?>> registry);
+  void register(ContentSerializerRegistry registry);
```
Comment (dimas-b) [inline versioned/spi/src/main/java/org/projectnessie/versioned/store/ContentSerializerBundle.java:25]: Well, unlike `Content.Type`, here we register serializer instances... Could you simply do `ServiceLoader.load(ContentSerializer.class)`? On the receiving side, we do not know specific type parameters anyway.

Comment (snazy) [reply versioned/spi/src/main/java/org/projectnessie/versioned/store/ContentSerializerBundle.java:25]: But why have another approach here?

Comment (dimas-b) [reply versioned/spi/src/main/java/org/projectnessie/versioned/store/ContentSerializerBundle.java:25]: Do remove an extra interface... but this is a minor point, optional.

File: api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.projectnessie.model.types;
+
+import org.projectnessie.model.Content;
+
+/** An implementation of this interface is passed to {@link ContentTypeBundle}s. */
+public interface ContentTypeRegistry {
+  void register(Class<? extends Content> type);
```
[the remark this answers is not in the document]
Comment (dimas-b) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: The Json part is fine, I think. My concern is only about the Open API spec (which has its own discriminators in the schema annotation on `Content`).

Since we now expect custom types to be present, is it worth declaring a sub-set of possible types as `oneOf` in our Open API spec?

[the remark this answers is not in the document]
Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: Define "possible types" ;)

The problem is that we cannot dynamically extend that `oneOf` + the OpenAPI discriminators. OTOH, it's only "an issue" for new/completely-custom-private types. New "core" types will naturally be added there.

[the remark this answers is not in the document]
Comment (dimas-b) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: Why would we want to keep `oneOf` in the Open API spec at all? With pluggable types, the spec is guaranteed to be skewed sooner or later. 

I'm proposing to replace it with a generic `Object` type (or the Open API) equivalent.

[the remark this answers is not in the document]
Comment (adutra) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: I think this could become a problem for the future Event API. The generated JSON schema for this API currently has this:

```json
      "Content" : {
        "title" : "Content",
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          }
        },
        "oneOf" : [ {
          "$ref" : "#/components/schemas/IcebergTable"
        }, {
          "$ref" : "#/components/schemas/DeltaLakeTable"
        }, {
          "$ref" : "#/components/schemas/IcebergView"
        }, {
          "$ref" : "#/components/schemas/Namespace"
        } ],
        "discriminator" : {
          "propertyName" : "type",
          "mapping" : {
            "ICEBERG_TABLE" : "#/components/schemas/IcebergTable",
            "DELTA_LAKE_TABLE" : "#/components/schemas/DeltaLakeTable",
            "ICEBERG_VIEW" : "#/components/schemas/IcebergView",
            "NAMESPACE" : "#/components/schemas/Namespace"
          }
        }
      },
```

The `oneOf` approach will be problematic if someone uses this schema to attempt a polymorphic deserialization of components of different types, for example when using `KafkaJsonSchemaDeserializer` to deserialize events from a Kafka topic.

Even if the consumer has the jar containing the custom content implementation, the schema won't allow it, and deserializing such a content is likely to fail imho.

(However, I _think_ this could work when using a schema-less deserializer like `KafkaJsonDeserializer`.)

[the remark this answers is not in the document]
Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: Hm - custom content-types aren't new though. Not sure why events infra needs to know the whole model.

[the remark this answers is not in the document]
Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/types/ContentTypeRegistry.java:22]: > perhaps replace with anyOf(coreType1, coreType2, ..., Object).

`anyOf` seems to work

File: api/model/src/main/java/org/projectnessie/model/Content.java [hunk 5]
```diff
@@ -34,7 +35,13 @@
 @Schema(
     type = SchemaType.OBJECT,
     title = "Content",
-    oneOf = {IcebergTable.class, DeltaLakeTable.class, IcebergView.class, Namespace.class},
+    anyOf = {
+      IcebergTable.class,
+      DeltaLakeTable.class,
+      IcebergView.class,
+      Namespace.class,
+      Map.class
```
Comment (dimas-b) [inline api/model/src/main/java/org/projectnessie/model/Content.java:43]: nit: this does not have a name in Swagger / Open API yaml:
```
    Content_V2:
      title: Content
      type: object
      properties:
        id:
          type: string
      anyOf:
      - $ref: '#/components/schemas/IcebergTable_V2'
      - $ref: '#/components/schemas/DeltaLakeTable_V2'
      - $ref: '#/components/schemas/IcebergView_V2'
      - $ref: '#/components/schemas/Namespace_V2'
      - type: object
```
not a big deal, but perhaps we can name it "Custom Content" (latger)

**Review by dimas-b — APPROVED** [review]

File: api/model/src/main/java/org/projectnessie/model/Content.java (hunk 5 above)
Comment (snazy) [reply api/model/src/main/java/org/projectnessie/model/Content.java:43]: Can't put a "name" for it :(
