### PR TITLE
Do not store intermediate commits during merge/transplant

### LINKED ISSUE #6674: Dry-run Merge still makes writes in the New Model
1. Generate some commits on a branch (does not matter what exactly)
2. Run a "dry run" merge attempt:
```
$ curl -H 'content-type: application/json' -X POST \
  http://localhost:19120/api/v2/trees/main@2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d/history/merge \
 -d '{"fromRefName":"dev1", "fromHash":"10c1d5a6184846c714e46f451116d2fa6c487a9f9e7b506350d826da4c258d54", "isDryRun":"true"}'
```
3. As a result the following object is stored (observed in a java debugger):
```
CommitObj{id=b41a16b5200afa19af7eaa889c469e6ee051ae8492a0be4545e969f690b03b1a, created=1682355825858820, seq=5, tail=[f553cc944d05760e0ca5a335485ba5297e3de2c970f985aeab6484da511cd523, ebc51f8cf8d34256c00d8698b6736ad845119b9ef102a6a07e2d33baa5ca761f, 6e3754d174c0d8e3e5ea6953b7d9db73f793430488e1e37ae546bd23f6e0eb51, c1235f747bcb4d24b7b9c4752d963018a0694448527b82ca3fec8d3951505988, 2e1cfa82b035c26cbbbdae632cea070514eb8b773f616aaeaf668e2f0be8f10d], secondaryParents=[10c1d5a6184846c714e46f451116d2fa6c487a9f9e7b506350d826da4c258d54], headers=CommitHeaders{date=[2023-04-24T17:03:45.857681Z],author-date=[2023-04-24T17:01:29.780322Z],committer=[],author=[test]}, message=Create namespace key: ns3, incompleteIndex=false, referenceIndexStripes=[], incrementalIndex=<ByteString@296280ae size=118 contents="\001M\000ns2\000C\000\000a\004 \202\301\323\032l\347\254\273\000\201\002\346a\232W%FP\361]\217nw\337Pn\361j]|\211\226\371`...">, commitType=NORMAL}
```
4. Stack trace:
```
java.lang.Exception: test
	at org.projectnessie.versioned.storage.inmemory.InmemoryPersist.storeObj(InmemoryPersist.java:265)
	at org.projectnessie.versioned.storage.common.persist.Persist.storeObj(Persist.java:236)
	at org.projectnessie.versioned.storage.inmemory.InmemoryPersist.storeObjs(InmemoryPersist.java:276)
	at org.projectnessie.versioned.storage.telemetry.TelemetryPersist.storeObjs(TelemetryPersist.java:262)
	at org.projectnessie.versioned.storage.cache.CachingPersistImpl.storeObjs(CachingPersistImpl.java:150)
	at org.projectnessie.versioned.storage.telemetry.TelemetryPersist.storeObjs(TelemetryPersist.java:262)
	at org.projectnessie.versioned.storage.common.logic.CommitLogicImpl.storeCommit(CommitLogicImpl.java:299)
	at org.projectnessie.versioned.storage.versionstore.BaseMergeTransplantSquash.squash(BaseMergeTransplantSquash.java:100)
	at org.projectnessie.versioned.storage.versionstore.MergeSquashImpl.merge(MergeSquashImpl.java:70)
	at org.projectnessie.versioned.storage.versionstore.VersionStoreImpl.lambda$merge$6(VersionStoreImpl.java:629)
	at org.projectnessie.versioned.storage.versionstore.BaseCommitHelper.lambda$committingOperation$0(BaseCommitHelper.java:192)
	at org.projectnessie.versioned.storage.common.logic.CommitRetry.commitRetry(CommitRetry.java:50)
	at org.projectnessie.versioned.storage.common.logic.CommitRetry.commitRetry(CommitRetry.java:38)
	at org.projectnessie.versioned.storage.versionstore.BaseCommitHelper.committingOperation(BaseCommitHelper.java:177)
	at org.projectnessie.versioned.storage.versionstore.VersionStoreImpl.merge(VersionStoreImpl.java:622)
	at org.projectnessie.versioned.TracingVersionStore.lambda$merge$8(TracingVersionStore.java:180)
	at org.projectnessie.versioned.TracingVersionStore.callWithTwoExceptions(TracingVersionStore.java:387)
	at org.projectnessie.versioned.TracingVersionStore.merge(TracingVersionStore.java:173)
	at org.projectnessie.versioned.MetricsVersionStore.lambda$merge$3(MetricsVersionStore.java:147)
	at org.projectnessie.versioned.MetricsVersionStore.delegate2ExR(MetricsVersionStore.java:337)
	at org.projectnessie.versioned.MetricsVersionStore.merge(MetricsVersionStore.java:144)
	at org.projectnessie.services.impl.TreeApiImpl.mergeRefIntoBranch(TreeApiImpl.java:639)
	at org.projectnessie.services.rest.RestTreeService_Subclass.mergeRefIntoBranch$$superforward1(Unknown Source)
	at org.projectnessie.services.rest.RestTreeService_Subclass$$function$$4.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.projectnessie.services.rest.RestTreeService_Subclass.mergeRefIntoBranch(Unknown Source)
	at org.projectnessie.services.rest.RestTreeService_ClientProxy.mergeRefIntoBranch(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource.mergeRefIntoBranch(RestV2TreeResource.java:344)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass.mergeRefIntoBranch$$superforward1(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass$$function$$8.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:35)
	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor.restMethodInvoke(QuarkusRestPathTemplateInterceptor.java:39)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:33)
	at org.projectnessie.services.rest.RestV2TreeResource_Subclass.mergeRefIntoBranch(Unknown Source)
	at org.projectnessie.services.rest.RestV2TreeResource_ClientProxy.mergeRefIntoBranch(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by dimas-b**
* Do not store objects during dry runs.

* Do not store objects when conflicts are detected.

Use a BatchingPersist during unsquashed merge/transplant execution and
flush only on success. This is to allow CommitLogic to 'see'
intermediate commits without writing them to storage. Batching writes in
this case is a secondary effect.

Move PersistDelegate to top level.

Add test tooling to allow validating whether any storage writes happened
since a checkpoint.

Also add a test case to make sure dry run merge/transplant operations
at the API level.

Note: exact response messages differ between old and new model in
this case, but substantial information is the same (keys from the
merge/transplant request).

Fixes #6674

### CODE REVIEW

**Review by adutra — DISMISSED** [review]

File: servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java [hunk 1]
```diff
@@ -521,6 +522,57 @@ public void commitMergeTransplant() throws Exception {
         .containsKeys(ContentKey.of("a", "a"), ContentKey.of("b", "a"), ContentKey.of("b", "b"));
   }
 
+  @Test
+  public void mergeTransplantDryRunWithConflicts() throws Exception {
```
Comment (snazy) [inline servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: Guess this test should better live in `org.projectnessie.versioned.tests.AbstractMerge`

Comment (dimas-b) [reply servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: Do we not want end-to-end validation for `dryRun` handling? I did not see any other API-level test that exercised `dryRun` parameters.

Comment (snazy) [reply servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: Hm - then maybe have it in both places. A simple one in `o.p.jaxrs.tests` validating `dryRun` and the functional one in `o.p.versioned.tests`.

The benefit of having it in `org.projectnessie.versioned.tests` is that it's easily debuggable w/o the REST overhead (and thread "jumps").

Comment (dimas-b) [reply servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: will do

Comment (dimas-b) [reply servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: Does #6685 cover what you meant, @snazy ?

Comment (snazy) [reply servers/jax-rs-tests/src/main/java/org/projectnessie/jaxrs/tests/BaseTestNessieApi.java:526]: That's more than I thought of - but great stuff :)

**Review by snazy — APPROVED** [review]

**Review by snazy — APPROVED** [review]
