### PR TITLE
SQL Extension: Fix Create reference from a hash on non-default reference

### LINKED ISSUE #3659: SQL Extension: Failure in Create reference from a hash on non-default reference
CREATE BRANCH dev IN nessie FROM MAIN;
USE REFERENCE dev IN nessie
CREATE TABLE nessie.db.tbl (id int, name string)
INSERT INTO nessie.db.tbl select 23, "test"
CREATE BRANCH test IN nessie FROM dev; --> fails as it looks for dev's latest hash in 'main' branch instead of 'dev' branch.

`Could not find commit '0eed82af48bbb879055b477862d9f9ec0ac1c975ca46e1ff373463bc700a2568' in reference 'main'.
`

Reason: Source ref name is not set in the code. Hence, it is looking for default reference.

### PR DESCRIPTION
**Pull request by ajantha-bhat**
_Steps to reproduce:_
CREATE BRANCH dev IN nessie FROM main;
USE REFERENCE dev IN nessie
CREATE TABLE nessie.db.tbl (id int, name string)
INSERT INTO nessie.db.tbl select 23, "test"
CREATE BRANCH test IN nessie FROM dev; --> fails as it looks for dev's latest hash in 'main' branch instead of 'dev' branch.

Could not find commit '0eed82af48bbb879055b477862d9f9ec0ac1c975ca46e1ff373463bc700a2568' in reference 'main'.

`Reason`: Source ref name is not set in the code. Hence, it is looking for default reference. There was no testcase to catch this scenario. 

Fixes #3659

### CODE REVIEW

File: clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java [hunk 1]
```diff
@@ -299,6 +299,48 @@ void testCreateTagInFrom() throws NessieNotFoundException {
...
+
+    String tempRef = refName + "_temp";
+    sql("CREATE BRANCH %s IN nessie FROM %s", tempRef, refName);
+    assertThat(api.getReference().refName(tempRef).get()).isEqualTo(Branch.of(tempRef, newHash));
+
+    String tag = refName + "_temp_tag";
+    sql("CREATE TAG %s IN nessie FROM %s", tag, refName);
+    assertThat(api.getReference().refName(tag).get()).isEqualTo(Tag.of(tag, newHash));
+
+    assertThat(sql("DROP BRANCH %s IN nessie", refName)).containsExactly(row("OK"));
```
Comment (nastra) [inline clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:328]: those 3 DROP statements aren't really needed as they are being cleaned up automatically

Comment (ajantha-bhat) [reply clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:328]: other testcases also has the same pattern. So, I followed the same.

Comment (nastra) [reply clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:328]: yes I know, and this should rather be cleaned up. We should just have separate tests for dropping a branch/tag and not pollute existing tests with drop statements

**Review by nastra — APPROVED** [review]

File: clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java (hunk 1 above)
Comment (ajantha-bhat) [reply clients/spark-extensions-base/src/test/java/org/projectnessie/spark/extensions/AbstractSparkSqlTest.java:328]: testCreateBranch, testCreateTag, testCreateBranchIn, testCreateTagIn, testCreateBranchInFrom, testCreateTagInFrom
all these has it, should I remove from them aswell or let's keep it?
