### PR TITLE
Retry erase repo with non-admin path if DropRowRange fails

### LINKED ISSUE #7347: Error when importing repo to BigTable
**What happened**:

Observed the below error when importing a repo to BigTable:

```
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: A DropRowRange operation is already ongoing.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:578)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:548)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.bigtable.admin.v2.BigtableTableAdminClient.dropRowRange(BigtableTableAdminClient.java:736)
		at org.projectnessie.versioned.storage.bigtable.BigTableBackend.eraseRepositoriesAdminClient(BigTableBackend.java:169)
		at org.projectnessie.versioned.storage.bigtable.BigTableBackend.eraseRepositories(BigTableBackend.java:157)
		at org.projectnessie.versioned.storage.bigtable.BigTablePersist.erase(BigTablePersist.java:547)
		at org.projectnessie.versioned.storage.cache.CachingPersistImpl.erase(CachingPersistImpl.java:207)
		at org.projectnessie.quarkus.cli.ImportRepository.callWithPersist(ImportRepository.java:189)
		at org.projectnessie.quarkus.cli.BaseCommand.call(BaseCommand.java:55)
		at org.projectnessie.quarkus.cli.BaseCommand.call(BaseCommand.java:33)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
		at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
		at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
		at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
		at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: A DropRowRange operation is already ongoing.
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 14 more
```

**What you expected to happen**:

No errors.

**How to reproduce it (as minimally and precisely as possible)**:

I will work on getting a clean reproducer but the error doesn't manifest deterministically it seems.

**Details**:
- Nessie server type (docker/built from source) and version: 0.65
- Client type (Ex: UI/Spark/pynessie ...) and version:

### LINKED ISSUE #7351: BigTable: erase repo fails occasionally when DropRowRange quota exceeded
**What happened**:

The DropRowRange admin operation is used to erase a repo, but it is rate-limited. Occasionally, the operation will fail with the below error:

```
com.google.api.gax.rpc.ResourceExhaustedException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'DropRowRange requests' and limit 'DropRowRange requests per day' of service 'bigtableadmin.googleapis.com' for consumer 'project_number:XYZ'.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:100)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:578)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:548)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.cloud.bigtable.admin.v2.BigtableTableAdminClient.dropRowRange(BigtableTableAdminClient.java:736)
		at org.projectnessie.versioned.storage.bigtable.BigTableBackend.eraseRepositoriesAdminClient(BigTableBackend.java:169)
		at org.projectnessie.versioned.storage.bigtable.BigTableBackend.eraseRepositories(BigTableBackend.java:157)
		at org.projectnessie.versioned.storage.bigtable.BigTablePersist.erase(BigTablePersist.java:547)
		at org.projectnessie.versioned.storage.cache.CachingPersistImpl.erase(CachingPersistImpl.java:207)
		at org.projectnessie.quarkus.cli.ImportRepository.callWithPersist(ImportRepository.java:189)
		at org.projectnessie.quarkus.cli.BaseCommand.call(BaseCommand.java:55)
		at org.projectnessie.quarkus.cli.BaseCommand.call(BaseCommand.java:33)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
		at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
		at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
		at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
		at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'DropRowRange requests' and limit 'DropRowRange requests per day' of service 'bigtableadmin.googleapis.com' for consumer 'project_number:XYZ'.
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 14 more
```

**What you expected to happen**:

Instead of failing, we could try the non-admin path first as it has a non-zero chance of success.

**How to reproduce it (as minimally and precisely as possible)**:

Just hit the quota.

**Details**:
- Nessie server type (docker/built from source) and version:
- Client type (Ex: UI/Spark/pynessie ...) and version:

### PR DESCRIPTION
**Pull request by adutra**
Fixes #7351 
Fixes #7347

### CODE REVIEW

File: versioned/storage/bigtable/src/main/java/org/projectnessie/versioned/storage/bigtable/BigTableBackend.java [hunk 1]
```diff
@@ -166,8 +168,16 @@ private boolean eraseRepositoriesAdminClient(Set<String> repositoryIds) {
...
     for (String repoId : repositoryIds) {
       ByteString prefix = copyFromUtf8(repoId + ':');
-      tableAdminClient.dropRowRange(tableRefs, prefix);
-      tableAdminClient.dropRowRange(tableObjs, prefix);
+      try {
+        tableAdminClient.dropRowRange(tableRefs, prefix);
+        tableAdminClient.dropRowRange(tableObjs, prefix);
+      } catch (ResourceExhaustedException e) {
+        LOGGER.warn("DropRowRange quota exceeded, trying the non-admin path", e);
+        return false;
```
Comment (snazy) [inline versioned/storage/bigtable/src/main/java/org/projectnessie/versioned/storage/bigtable/BigTableBackend.java:176]: I think we don't want to re-delete the repo-Ids that have already been processed here. WDYT?

File: versioned/storage/bigtable/src/main/java/org/projectnessie/versioned/storage/bigtable/BigTableBackend.java [hunk 2]
```diff
@@ -154,32 +157,37 @@ private void checkTable(String table, String family) {
...
+        String repoId = repositoryIds.get(0);
+        ByteString prefix = copyFromUtf8(repoId + ':');
+        try {
+          tableAdminClient.dropRowRange(tableRefs, prefix);
+          tableAdminClient.dropRowRange(tableObjs, prefix);
+        } catch (ApiException e) {
+          LOGGER.warn("Could not erase repo with admin client, switching to data client", e);
+          return;
+        }
+        repositoryIds.remove(repoId);
```
Comment (dimas-b) [inline versioned/storage/bigtable/src/main/java/org/projectnessie/versioned/storage/bigtable/BigTableBackend.java:177]: nit: maybe use a `Queue` instead (for a more natural interface)?

**Review by dimas-b — APPROVED** [review]

**Review by dimas-b — APPROVED** [review]
